name: batch_scanner_mobile
description: A mobile batch scanner app for pharmaceutical inventory management.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP client
  http: ^1.2.0
  
  # QR code scanning (latest version compatible with AGP 8.x)
  mobile_scanner: ^5.0.0
  
  # Camera functionality
  camera: ^0.11.0
  
  # OCR using Google ML Kit (mobile optimized)
  google_mlkit_text_recognition: ^0.13.0
  
  # Local database
  sqflite: ^2.3.0
  
  # Local storage
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Image picking
  image_picker: ^1.0.7
  
  # State management
  flutter_riverpod: ^2.4.0
  
  # JSON handling
  json_annotation: ^4.9.0
  
  # Path utilities
  path: ^1.9.0
  
  # String matching (for local batch matching)
  fuzzywuzzy: ^1.1.6
  
  # Date formatting
  intl: ^0.19.0
  
  # Material design icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation tools (if needed later)
  # build_runner: ^2.4.7
  # freezed: ^2.4.6
  # json_serializable: ^6.7.1

  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Uncomment when assets are added
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # App icon
  # flutter_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/icons/app_icon.png"
